const {Profile, ProfileIdentification, ProfileInterests} = require("./profileModels")
const Message = require("./messageModels")
const Activity = require("./activityModels")
const {Exercise, Workout, WorkoutDay, WorkoutProgram} = require("./workoutModels")

Message.hasOne(Profile, {foreignKey: "id", as: "sender"})
Message.hasOne(Profile, {foreignKey: "id", as: "receiver"})
Profile.hasMany(Message)

Activity.belongsTo(Profile)
Activity.belongsTo(Exercise)
Activity.belongsTo(Workout)
Exercise.hasMany(Activity)
Workout.hasMany(Activity)
Profile.hasMany(Activity)

Profile.hasOne(ProfileIdentification)
ProfileIdentification.belongsTo(Profile)
Profile.hasOne(ProfileInterests)
ProfileInterests.belongsTo(Profile)
Profile.belongsToMany(Profile, {through: "profileFriends", as: "friends"})
ProfileInterests.belongsToMany(WorkoutProgram, {through: "profileInterestsProgram"})
WorkoutProgram.belongsToMany(ProfileInterests, {through: "profileInterestsProgram"})
ProfileInterests.belongsToMany(Workout, {through: "profileInterestsWorkout"})
Workout.belongsToMany(ProfileInterests, {through: "profileInterestsWorkout"})

Exercise.belongsToMany(Workout, {through: "exerciseWorkout"})
Workout.belongsToMany(Exercise, {through: "exerciseWorkout"})
Exercise.belongsToMany(WorkoutProgram, {through: "exerciseWorkoutProgram"})
WorkoutProgram.belongsToMany(Exercise, {through: "exerciseWorkoutProgram"})
Exercise.belongsToMany(WorkoutDay, {through: "exerciseWorkoutDay"})
WorkoutDay.belongsToMany(Exercise, {through: "exerciseWorkoutDay"})
Workout.belongsToMany(WorkoutDay, {through: "workoutWorkoutDay"})
WorkoutDay.belongsToMany(Workout, {through: "workoutWorkoutDay"})
WorkoutDay.belongsToMany(WorkoutProgram, {through: "workoutDayProgram"})
WorkoutProgram.belongsToMany(WorkoutDay, {through: "workoutDayProgram"})