
exports.GENDER_EUNUM = {
    NO_INFO: "NO INFO",
    MALE: "MALE",
    FEMALE: "FEMALE",
    SOMETHING_ELSE: "SOMETHING ELSE"
}

exports.GENDER_ENUM_LIST = ["NO INFO", "MALE", "FEMALE", "SOMETHING ELSE"]
exports.UNIT_ENUM_LIST = ["METRIC", "IMPERIAL"]
exports.PRIVACY_ENUM_LIST = ["PUBLIC", "PRIVATE"]