
exports.GENDER_EUNUM = {
    NO_INFO: "NO INFO",
    MALE: "MALE",
    FEMALE: "FEMALE",
    SOMETHING_ELSE: "OTHER"
}

exports.GENDER_ENUM_LIST = ["NOINFO", "MALE", "FEMALE", "OTHER"]
exports.UNIT_ENUM_LIST = ["METRIC", "IMPERIAL"]
exports.PRIVACY_ENUM_LIST = ["PUBLIC", "PRIVATE"]